### ISSUE TITLE
Create example issues for testing and development

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/gh-issue-map#1]
👋 

```[tasklist]
### Tasks
- [x] Create an issue (this one!)
- [ ] https://github.com/solvaholic/gh-issue-map/issues/2
- [ ] https://github.com/solvaholic/gh-issue-map/issues/3
- [x] Mention a user in #1
```

**Comment by solvaholic** [comment]
Hey @otherroger are you available to help with this?
