### ISSUE TITLE
Create gh-issue-map Script

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/gh-issue-map#4]
* The map is a graph?
* Nodes: Issue
* Edges: LinksTo, LinkedFrom

```[tasklist]
### Tasks
- [x] Get issue body and comments
- [x] Extract issues this issue LinksTo (these appear in body and comments)
- [x] Get issue timeline
- [x] Extract issues this issue is LinkedFrom (these appear as cross-references)
```

**Comment by solvaholic** [comment]
Ran `gh extension install .` in my clone of this repo. Then:

```text
% gh issue-map 1
Links to:
https://github.com/solvaholic/gh-issue-map/issues/1
https://github.com/solvaholic/gh-issue-map/issues/2
https://github.com/solvaholic/gh-issue-map/issues/3

Linked from:
https://github.com/solvaholic/gh-issue-map/issues/3
```

```text
% gh issue-map 2
Links to:


Linked from:
https://github.com/solvaholic/gh-issue-map/issues/1
https://github.com/solvaholic/gh-issue-map/issues/3
```

```text
% gh issue-map 3
Links to:
https://github.com/solvaholic/gh-issue-map/issues/3

Linked from:
https://github.com/solvaholic/gh-issue-map/issues/1
```

**Comment by solvaholic** [comment]
Tidied that up a bit:

```text
% gh issue-map 2
Linked from:
https://github.com/solvaholic/gh-issue-map/issues/1
https://github.com/solvaholic/gh-issue-map/issues/3
```
