### ISSUE TITLE
Improve gh-issue-map

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/gh-issue-map#5]
```[tasklist]
### Tasks
- [ ] https://github.com/solvaholic/gh-issue-map/issues/4
- [x] Handle arguments `--verbose` and `--help`
- [x] Add Markdown table output option
- [ ] Add JSON output option
- [ ] Render JSON output in a browser
- [ ] Use the --verbose option, or remove it
```

Test with issues 1, 2, and 3:

```shell
for i in 1 2 3; do
  printf "# Map issue $i\n"
  gh issue-map $i
done
```

**Comment by solvaholic** [comment]
:tada:

```text
% gh issue-map --table 1
| Links To | Linked From |
|----------|-------------|
| https://github.com/solvaholic/gh-issue-map/issues/1 | https://github.com/solvaholic/gh-issue-map/issues/3 |
| https://github.com/solvaholic/gh-issue-map/issues/2 |             |
| https://github.com/solvaholic/gh-issue-map/issues/3 |             |
```

**Comment by solvaholic** [comment]
The GraphQL query in this gist returns tracking/tracked-in details, and may be easier to work with:
https://gist.github.com/solvaholic/4a083c860f0ef0c60789b6c826d62e8b
